# ********RoostGPT********
"""
Test generated by RoostGPT for test deepseek using AI Type deepseek_ai and AI Model deepseek-chat

Test generated by RoostGPT for test deepseek using AI Type deepseek_ai and AI Model deepseek-chat

ROOST_METHOD_HASH=split_data_9459bd973e
ROOST_METHOD_SIG_HASH=split_data_213d87dc1e


### Test Scenarios for `split_data` Method

#### Scenario 1: Splitting a CSV File into Multiple Files Based on Split Number
**Details:**
  - **TestName:** test_split_csv_file
  - **Description:** This test verifies that the `split_data` method correctly splits a CSV file into multiple smaller files based on the provided split number. The method should create new files in the specified directory, each containing the number of rows equal to the split number, except possibly the last file.

**Execution:**
  - **Arrange:** 
    - Create a CSV file with a known number of rows (e.g., 10 rows).
    - Initialize the `Split_Files` class with the CSV file name and a split number (e.g., 3).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory contains the correct number of split files (e.g., 4 files for 10 rows with a split number of 3).
    - Check that each file (except possibly the last) contains exactly 3 rows.
    - Ensure the last file contains the remaining rows (e.g., 1 row).

**Validation:**
  - **Rationale:** This test ensures that the core functionality of splitting a CSV file works as expected, which is critical for processing large datasets in manageable chunks.

#### Scenario 2: Splitting a TXT File into Multiple Files Based on Split Number
**Details:**
  - **TestName:** test_split_txt_file
  - **Description:** This test verifies that the `split_data` method correctly splits a TXT file into multiple smaller files based on the provided split number. The method should create new files in the specified directory, each containing the number of rows equal to the split number, except possibly the last file.

**Execution:**
  - **Arrange:** 
    - Create a TXT file with a known number of rows (e.g., 10 rows).
    - Initialize the `Split_Files` class with the TXT file name and a split number (e.g., 4).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory contains the correct number of split files (e.g., 3 files for 10 rows with a split number of 4).
    - Check that each file (except possibly the last) contains exactly 4 rows.
    - Ensure the last file contains the remaining rows (e.g., 2 rows).

**Validation:**
  - **Rationale:** This test ensures that the method can handle TXT files correctly, which is important for applications that process text data.

#### Scenario 3: Handling an Empty File
**Details:**
  - **TestName:** test_split_empty_file
  - **Description:** This test verifies that the `split_data` method handles an empty file correctly. The method should not create any split files if the input file is empty.

**Execution:**
  - **Arrange:** 
    - Create an empty CSV or TXT file.
    - Initialize the `Split_Files` class with the empty file name and a split number (e.g., 5).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory is empty (no split files are created).

**Validation:**
  - **Rationale:** This test ensures that the method gracefully handles edge cases where the input file contains no data, preventing unnecessary file creation.

#### Scenario 4: Handling a File with Fewer Rows Than the Split Number
**Details:**
  - **TestName:** test_split_file_with_fewer_rows_than_split_number
  - **Description:** This test verifies that the `split_data` method correctly handles a file where the number of rows is less than the split number. The method should create a single file containing all the rows.

**Execution:**
  - **Arrange:** 
    - Create a CSV or TXT file with fewer rows than the split number (e.g., 2 rows).
    - Initialize the `Split_Files` class with the file name and a split number (e.g., 5).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory contains a single file.
    - Check that the file contains all the rows from the original file.

**Validation:**
  - **Rationale:** This test ensures that the method correctly handles cases where the input file is smaller than the specified split size, which is important for avoiding unnecessary file splits.

#### Scenario 5: Handling a File with Exactly the Number of Rows as the Split Number
**Details:**
  - **TestName:** test_split_file_with_exact_rows_as_split_number
  - **Description:** This test verifies that the `split_data` method correctly handles a file where the number of rows is exactly equal to the split number. The method should create a single file containing all the rows.

**Execution:**
  - **Arrange:** 
    - Create a CSV or TXT file with the number of rows equal to the split number (e.g., 5 rows).
    - Initialize the `Split_Files` class with the file name and a split number (e.g., 5).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory contains a single file.
    - Check that the file contains all the rows from the original file.

**Validation:**
  - **Rationale:** This test ensures that the method correctly handles cases where the input file size matches the split size, which is important for ensuring consistent behavior.

#### Scenario 6: Handling a File with a Large Number of Rows
**Details:**
  - **TestName:** test_split_large_file
  - **Description:** This test verifies that the `split_data` method can handle a file with a large number of rows (e.g., 1000 rows) and correctly splits it into multiple files based on the split number.

**Execution:**
  - **Arrange:** 
    - Create a CSV or TXT file with a large number of rows (e.g., 1000 rows).
    - Initialize the `Split_Files` class with the file name and a split number (e.g., 100).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory contains the correct number of split files (e.g., 10 files for 1000 rows with a split number of 100).
    - Check that each file (except possibly the last) contains exactly 100 rows.
    - Ensure the last file contains the remaining rows (e.g., 0 rows if the total is divisible by the split number).

**Validation:**
  - **Rationale:** This test ensures that the method can handle large datasets efficiently, which is critical for performance in real-world applications.

#### Scenario 7: Handling a File with Non-Standard Delimiters (TXT File)
**Details:**
  - **TestName:** test_split_txt_file_with_non_standard_delimiter
  - **Description:** This test verifies that the `split_data` method correctly handles a TXT file with non-standard delimiters (e.g., tabs or custom delimiters). The method should correctly split the file based on the provided split number.

**Execution:**
  - **Arrange:** 
    - Create a TXT file with non-standard delimiters (e.g., tabs) and a known number of rows (e.g., 10 rows).
    - Initialize the `Split_Files` class with the TXT file name and a split number (e.g., 3).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory contains the correct number of split files (e.g., 4 files for 10 rows with a split number of 3).
    - Check that each file (except possibly the last) contains exactly 3 rows.
    - Ensure the last file contains the remaining rows (e.g., 1 row).

**Validation:**
  - **Rationale:** This test ensures that the method can handle TXT files with non-standard delimiters, which is important for flexibility in processing different types of text data.

#### Scenario 8: Handling a File with Missing or Corrupted Data
**Details:**
  - **TestName:** test_split_file_with_missing_or_corrupted_data
  - **Description:** This test verifies that the `split_data` method correctly handles a file with missing or corrupted data. The method should still split the file based on the provided split number, ignoring or handling the corrupted rows appropriately.

**Execution:**
  - **Arrange:** 
    - Create a CSV or TXT file with some missing or corrupted rows (e.g., rows with incomplete data or incorrect formatting).
    - Initialize the `Split_Files` class with the file name and a split number (e.g., 5).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory contains the correct number of split files.
    - Check that each file (except possibly the last) contains the expected number of rows, ignoring or handling the corrupted rows.

**Validation:**
  - **Rationale:** This test ensures that the method can handle real-world data issues, such as missing or corrupted data, which is important for robustness in data processing applications.

#### Scenario 9: Handling a File with a Single Row
**Details:**
  - **TestName:** test_split_file_with_single_row
  - **Description:** This test verifies that the `split_data` method correctly handles a file with only a single row. The method should create a single file containing that row.

**Execution:**
  - **Arrange:** 
    - Create a CSV or TXT file with a single row.
    - Initialize the `Split_Files` class with the file name and a split number (e.g., 5).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory contains a single file.
    - Check that the file contains the single row from the original file.

**Validation:**
  - **Rationale:** This test ensures that the method correctly handles edge cases where the input file contains only one row, which is important for ensuring consistent behavior.

#### Scenario 10: Handling a File with a Very Large Split Number
**Details:**
  - **TestName:** test_split_file_with_very_large_split_number
  - **Description:** This test verifies that the `split_data` method correctly handles a file where the split number is larger than the number of rows in the file. The method should create a single file containing all the rows.

**Execution:**
  - **Arrange:** 
    - Create a CSV or TXT file with a known number of rows (e.g., 10 rows).
    - Initialize the `Split_Files` class with the file name and a very large split number (e.g., 100).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory contains a single file.
    - Check that the file contains all the rows from the original file.

**Validation:**
  - **Rationale:** This test ensures that the method correctly handles cases where the split number is larger than the file size, which is important for preventing unnecessary file splits.

#### Scenario 11: Handling a File with a Split Number of 1
**Details:**
  - **TestName:** test_split_file_with_split_number_1
  - **Description:** This test verifies that the `split_data` method correctly handles a file where the split number is 1. The method should create a separate file for each row in the input file.

**Execution:**
  - **Arrange:** 
    - Create a CSV or TXT file with a known number of rows (e.g., 5 rows).
    - Initialize the `Split_Files` class with the file name and a split number of 1.
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory contains a separate file for each row in the input file (e.g., 5 files for 5 rows).
    - Check that each file contains exactly one row.

**Validation:**
  - **Rationale:** This test ensures that the method correctly handles the edge case where the split number is 1, which is important for ensuring consistent behavior.

#### Scenario 12: Handling a File with a Split Number of 0
**Details:**
  - **TestName:** test_split_file_with_split_number_0
  - **Description:** This test verifies that the `split_data` method correctly handles a file where the split number is 0. The method should either raise an error or handle the case gracefully without creating any files.

**Execution:**
  - **Arrange:** 
    - Create a CSV or TXT file with a known number of rows (e.g., 5 rows).
    - Initialize the `Split_Files` class with the file name and a split number of 0.
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory is empty (no split files are created).
    - Optionally, check that an appropriate error is raised.

**Validation:**
  - **Rationale:** This test ensures that the method correctly handles invalid input (split number of 0), which is important for preventing unintended behavior.

#### Scenario 13: Handling a File with a Negative Split Number
**Details:**
  - **TestName:** test_split_file_with_negative_split_number
  - **Description:** This test verifies that the `split_data` method correctly handles a file where the split number is negative. The method should either raise an error or handle the case gracefully without creating any files.

**Execution:**
  - **Arrange:** 
    - Create a CSV or TXT file with a known number of rows (e.g., 5 rows).
    - Initialize the `Split_Files` class with the file name and a negative split number (e.g., -5).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory is empty (no split files are created).
    - Optionally, check that an appropriate error is raised.

**Validation:**
  - **Rationale:** This test ensures that the method correctly handles invalid input (negative split number), which is important for preventing unintended behavior.

#### Scenario 14: Handling a File with a Non-Integer Split Number
**Details:**
  - **TestName:** test_split_file_with_non_integer_split_number
  - **Description:** This test verifies that the `split_data` method correctly handles a file where the split number is not an integer. The method should either raise an error or handle the case gracefully without creating any files.

**Execution:**
  - **Arrange:** 
    - Create a CSV or TXT file with a known number of rows (e.g., 5 rows).
    - Initialize the `Split_Files` class with the file name and a non-integer split number (e.g., 2.5).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory is empty (no split files are created).
    - Optionally, check that an appropriate error is raised.

**Validation:**
  - **Rationale:** This test ensures that the method correctly handles invalid input (non-integer split number), which is important for preventing unintended behavior.

#### Scenario 15: Handling a File with a Split Number Greater Than the Maximum Integer Value
**Details:**
  - **TestName:** test_split_file_with_split_number_greater_than_max_int
  - **Description:** This test verifies that the `split_data` method correctly handles a file where the split number is greater than the maximum integer value. The method should either raise an error or handle the case gracefully without creating any files.

**Execution:**
  - **Arrange:** 
    - Create a CSV or TXT file with a known number of rows (e.g., 5 rows).
    - Initialize the `Split_Files` class with the file name and a split number greater than the maximum integer value (e.g., 2^63).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory is empty (no split files are created).
    - Optionally, check that an appropriate error is raised.

**Validation:**
  - **Rationale:** This test ensures that the method correctly handles edge cases where the split number is extremely large, which is important for preventing unintended behavior.

#### Scenario 16: Handling a File with a Split Number Equal to the Maximum Integer Value
**Details:**
  - **TestName:** test_split_file_with_split_number_equal_to_max_int
  - **Description:** This test verifies that the `split_data` method correctly handles a file where the split number is equal to the maximum integer value. The method should create a single file containing all the rows.

**Execution:**
  - **Arrange:** 
    - Create a CSV or TXT file with a known number of rows (e.g., 5 rows).
    - Initialize the `Split_Files` class with the file name and a split number equal to the maximum integer value (e.g., 2^63 - 1).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory contains a single file.
    - Check that the file contains all the rows from the original file.

**Validation:**
  - **Rationale:** This test ensures that the method correctly handles edge cases where the split number is extremely large but still within the valid range, which is important for ensuring consistent behavior.

#### Scenario 17: Handling a File with a Split Number Equal to the Number of Rows
**Details:**
  - **TestName:** test_split_file_with_split_number_equal_to_number_of_rows
  - **Description:** This test verifies that the `split_data` method correctly handles a file where the split number is equal to the number of rows in the file. The method should create a single file containing all the rows.

**Execution:**
  - **Arrange:** 
    - Create a CSV or TXT file with a known number of rows (e.g., 5 rows).
    - Initialize the `Split_Files` class with the file name and a split number equal to the number of rows (e.g., 5).
  - **Act:** 
    - Call the `split_data` method.
  - **Assert:** 
    - Verify that the output directory contains a single file.
    - Check that the file contains all the rows from the original file.

**Validation:**
  - **Rationale:** This test ensures
"""

# ********RoostGPT********
import sys
import os
import shutil
import pandas as pd
import pytest
from split_files import Split_Files

class Test_SplitFilesSplitData:
    @pytest.mark.smoke
    @pytest.mark.valid
    def test_split_csv_file(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("test.csv")
        csv_file.write("1\n2\n3\n4\n5\n6\n7\n8\n9\n10")
        split_number = 3
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 4
        for i in range(1, 4):
            file_path = os.path.join(split_files.directory, f"split_file{i}.csv")
            df = pd.read_csv(file_path, header=None)
            assert len(df) == 3
        file_path = os.path.join(split_files.directory, "split_file4.csv")
        df = pd.read_csv(file_path, header=None)
        assert len(df) == 1

    @pytest.mark.valid
    def test_split_txt_file(self, tmpdir):
        # Arrange
        txt_file = tmpdir.join("test.txt")
        txt_file.write("1\n2\n3\n4\n5\n6\n7\n8\n9\n10")
        split_number = 4
        split_files = Split_Files(str(txt_file), split_number)

        # Act
        split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 3
        for i in range(1, 3):
            file_path = os.path.join(split_files.directory, f"split_file{i}.txt")
            df = pd.read_csv(file_path, header=None, sep=' ')
            assert len(df) == 4
        file_path = os.path.join(split_files.directory, "split_file3.txt")
        df = pd.read_csv(file_path, header=None, sep=' ')
        assert len(df) == 2

    @pytest.mark.negative
    def test_split_empty_file(self, tmpdir):
        # Arrange
        empty_file = tmpdir.join("empty.csv")
        empty_file.write("")
        split_number = 5
        split_files = Split_Files(str(empty_file), split_number)

        # Act
        split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 0

    @pytest.mark.valid
    def test_split_file_with_fewer_rows_than_split_number(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("test.csv")
        csv_file.write("1\n2")
        split_number = 5
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 1
        file_path = os.path.join(split_files.directory, "split_file1.csv")
        df = pd.read_csv(file_path, header=None)
        assert len(df) == 2

    @pytest.mark.valid
    def test_split_file_with_exact_rows_as_split_number(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("test.csv")
        csv_file.write("1\n2\n3\n4\n5")
        split_number = 5
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 1
        file_path = os.path.join(split_files.directory, "split_file1.csv")
        df = pd.read_csv(file_path, header=None)
        assert len(df) == 5

    @pytest.mark.performance
    def test_split_large_file(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("large.csv")
        with open(str(csv_file), 'w') as f:
            for i in range(1000):
                f.write(f"{i}\n")
        split_number = 100
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 10
        for i in range(1, 10):
            file_path = os.path.join(split_files.directory, f"split_file{i}.csv")
            df = pd.read_csv(file_path, header=None)
            assert len(df) == 100
        file_path = os.path.join(split_files.directory, "split_file10.csv")
        df = pd.read_csv(file_path, header=None)
        assert len(df) == 0

    @pytest.mark.valid
    def test_split_txt_file_with_non_standard_delimiter(self, tmpdir):
        # Arrange
        txt_file = tmpdir.join("test.txt")
        txt_file.write("1\t2\t3\n4\t5\t6\n7\t8\t9\n10\t11\t12")
        split_number = 3
        split_files = Split_Files(str(txt_file), split_number)

        # Act
        split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 4
        for i in range(1, 4):
            file_path = os.path.join(split_files.directory, f"split_file{i}.txt")
            df = pd.read_csv(file_path, header=None, sep='\t')
            assert len(df) == 3
        file_path = os.path.join(split_files.directory, "split_file4.txt")
        df = pd.read_csv(file_path, header=None, sep='\t')
        assert len(df) == 1

    @pytest.mark.negative
    def test_split_file_with_missing_or_corrupted_data(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("corrupted.csv")
        csv_file.write("1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20")
        split_number = 5
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 4
        for i in range(1, 4):
            file_path = os.path.join(split_files.directory, f"split_file{i}.csv")
            df = pd.read_csv(file_path, header=None)
            assert len(df) == 5
        file_path = os.path.join(split_files.directory, "split_file4.csv")
        df = pd.read_csv(file_path, header=None)
        assert len(df) == 5

    @pytest.mark.valid
    def test_split_file_with_single_row(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("single.csv")
        csv_file.write("1")
        split_number = 5
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 1
        file_path = os.path.join(split_files.directory, "split_file1.csv")
        df = pd.read_csv(file_path, header=None)
        assert len(df) == 1

    @pytest.mark.negative
    def test_split_file_with_very_large_split_number(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("large_split.csv")
        csv_file.write("1\n2\n3\n4\n5")
        split_number = 100
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 1
        file_path = os.path.join(split_files.directory, "split_file1.csv")
        df = pd.read_csv(file_path, header=None)
        assert len(df) == 5

    @pytest.mark.valid
    def test_split_file_with_split_number_1(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("split_1.csv")
        csv_file.write("1\n2\n3\n4\n5")
        split_number = 1
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 5
        for i in range(1, 6):
            file_path = os.path.join(split_files.directory, f"split_file{i}.csv")
            df = pd.read_csv(file_path, header=None)
            assert len(df) == 1

    @pytest.mark.negative
    def test_split_file_with_split_number_0(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("split_0.csv")
        csv_file.write("1\n2\n3\n4\n5")
        split_number = 0
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        with pytest.raises(ValueError):
            split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 0

    @pytest.mark.negative
    def test_split_file_with_negative_split_number(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("negative_split.csv")
        csv_file.write("1\n2\n3\n4\n5")
        split_number = -5
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        with pytest.raises(ValueError):
            split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 0

    @pytest.mark.negative
    def test_split_file_with_non_integer_split_number(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("non_integer_split.csv")
        csv_file.write("1\n2\n3\n4\n5")
        split_number = 2.5
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        with pytest.raises(ValueError):
            split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 0

    @pytest.mark.negative
    def test_split_file_with_split_number_greater_than_max_int(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("max_int_split.csv")
        csv_file.write("1\n2\n3\n4\n5")
        split_number = 2**63
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        with pytest.raises(ValueError):
            split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 0

    @pytest.mark.valid
    def test_split_file_with_split_number_equal_to_max_int(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("max_int_split.csv")
        csv_file.write("1\n2\n3\n4\n5")
        split_number = 2**63 - 1
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 1
        file_path = os.path.join(split_files.directory, "split_file1.csv")
        df = pd.read_csv(file_path, header=None)
        assert len(df) == 5

    @pytest.mark.valid
    def test_split_file_with_split_number_equal_to_number_of_rows(self, tmpdir):
        # Arrange
        csv_file = tmpdir.join("equal_split.csv")
        csv_file.write("1\n2\n3\n4\n5")
        split_number = 5
        split_files = Split_Files(str(csv_file), split_number)

        # Act
        split_files.split_data()

        # Assert
        output_files = os.listdir(split_files.directory)
        assert len(output_files) == 1
        file_path = os.path.join(split_files.directory, "split_file1.csv")
        df = pd.read_csv(file_path, header=None)
        assert len(df) == 5
